[project]
name = "dify-file-chunk-spiliter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "markitdown[all]>=0.1.2",
    "sqlalchemy>=2.0.41",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
