apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret-user-{user_id}
  namespace: idiot-user-space
  labels:
    # 增加该标签以启用认证信息校验
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: juicefs-meta-{user_id}
  metaurl: postgres://postgres:juicefs-postgres@juicefs-postgres.idiot-user-space-storage.svc.cluster.local:5432/juicefs-user-{user_id} # access user specific database in postgres
  # 如果文件系统已经 format 好，并且不希望再 pod 中 再次 format，可以不填写 `storage`、`bucket` 参数
  # storage: minio
  # bucket: http://{minIO_server}/{bucket-name}
  # access-key: minio
  # secret-key: minio_password
  # juicefs format 命令参数
  # format-options: trash-days=1,block-size=4096

  # 为 Mount Pod 注入环境变量，比如时区（默认 UTC），或者文件系统的 RSA 加密口令
  # envs: "{TZ: Asia/Shanghai, JFS_RSA_PASSPHRASE: xxx}"
  # 如果文件系统启用了加密，还需要附上秘钥原文
  # encrypt_rsa_key: xxx