repo gitolite-admin
    RW+     =   admin

# === 项目内置仓库 ===
repo builtin_skills
    RW+     =   admin
    R       =   readonly

repo builtin_scripts
    RW+     =   admin
    R       =   readonly

repo builtin_sub_agents_def
    RW+     =   admin
    R       =   readonly
