server {
    listen 8143;

    # 设置 CORS 变量（跨域请求）
    set $cors_origin "";
    # 如果请求来自对本地前端开发服务器的访问
    if ($http_origin ~* "^http://localhost:5173$") {
        set $cors_origin $http_origin;
    }
    # 如果请求来自 openvpn 局域网内访问k8s中本机暴露的前端服务即 10.8.0.***
    if ($http_origin ~* "^http://10\.8\.0\.\d{1,3}:31174$") {
        set $cors_origin $http_origin;
    }

    location /api/ {
        include /etc/nginx/snippets/proxy_cors.inc;

        proxy_pass http://api:8000;
        proxy_read_timeout 3600s;

        # 禁用缓冲，确保 SSE 消息立即转发
        proxy_buffering off;
        proxy_cache off;

        # 允许最大 100MB 的请求体
        client_max_body_size 100M;
    }

    location /app-notification/ {
        include /etc/nginx/snippets/proxy_cors.inc;

        proxy_pass http://app-notification:8001;
    }

    location /prometheus/ {
        proxy_pass http://prometheus:9090;
    }

    # location /neo4j/ {
    #     proxy_pass http://neo4j:7474/browser;
    # }
}
