extensions:
  basicauth/langfuse:
    client_auth:
      username: ${env:LANGFUSE_PUBLIC_KEY}
      password: ${env:LANGFUSE_SECRET_KEY}

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # Prometheus scrape endpoint

  # otlp/jaeger:
  #   endpoint: jaeger:4317 # send to jaeger
  #   tls:
  #     insecure: true

  otlphttp/langfuse:
    endpoint: ${env:LANGFUSE_ENDPOINT:-http://langfuse-web.langfuse.svc.cluster.local:3000/api/public/otel}
    tls:
      insecure: true  # If using self-signed certificates
    auth:
      authenticator: basicauth/langfuse

connectors:
  spanmetrics:

processors:
  batch:

service:
  extensions: [basicauth/langfuse]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlphttp/langfuse]
    # pipeline for logfire otlp metrics
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    # The metrics pipeline receives generated span metrics from 'spanmetrics' connector
    # and pushes to Prometheus exporter, which makes them available for scraping on :8889.
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
