# !!! now is empty !!!


# ==== Example values.yaml ====

# kubeletDir: <kubelet-dir>

# image:
#   repository: registry.example.com/juicefs-csi-driver
# dashboardImage:
#   repository: registry.example.com/csi-dashboard
# sidecars:
#   livenessProbeImage:
#     repository: registry.example.com/k8scsi/livenessprobe
#   nodeDriverRegistrarImage:
#     repository: registry.example.com/k8scsi/csi-node-driver-registrar
#   csiProvisionerImage:
#     repository: registry.example.com/k8scsi/csi-provisioner
#   csiResizerImage:
#     repository: registry.example.com/k8scsi/csi-resizer

# ==== Install Command ====
# helm upgrade --install juicefs-csi-driver juicefs/juicefs-csi-driver -n kube-system -f ./helm-values.yaml